"""add live vehicle tracking columns

Revision ID: 7fc9e171596d
Revises: 13153ac082e5
Create Date: 2026-04-19 13:34:22.275150

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7fc9e171596d"
down_revision: str | Sequence[str] | None = "13153ac082e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("route_stops_route_id_fkey"), "route_stops", type_="foreignkey")
    op.create_foreign_key(None, "route_stops", "routes", ["route_id"], ["id"], ondelete="CASCADE")
    # Set existing rows to 'true' so the NOT NULL constraint passes
    op.add_column("routes", sa.Column("active", sa.Boolean(), server_default="true", nullable=False))
    op.alter_column("routes", "name", existing_type=sa.VARCHAR(length=200), nullable=False)
    op.add_column("vehicles", sa.Column("route_id", sa.Integer(), nullable=True))
    op.add_column("vehicles", sa.Column("last_lat", sa.Float(), nullable=True))
    op.add_column("vehicles", sa.Column("last_lon", sa.Float(), nullable=True))
    op.add_column("vehicles", sa.Column("speed", sa.Float(), nullable=True))
    op.add_column("vehicles", sa.Column("position_updated_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_vehicles_route_id"), "vehicles", ["route_id"], unique=False)
    op.create_foreign_key(None, "vehicles", "routes", ["route_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vehicles", type_="foreignkey")
    op.drop_index(op.f("ix_vehicles_route_id"), table_name="vehicles")
    op.drop_column("vehicles", "position_updated_at")
    op.drop_column("vehicles", "speed")
    op.drop_column("vehicles", "last_lon")
    op.drop_column("vehicles", "last_lat")
    op.drop_column("vehicles", "route_id")
    op.alter_column("routes", "name", existing_type=sa.VARCHAR(length=200), nullable=True)
    op.drop_column("routes", "active")
    op.drop_constraint(None, "route_stops", type_="foreignkey")
    op.create_foreign_key(op.f("route_stops_route_id_fkey"), "route_stops", "routes", ["route_id"], ["id"])
    # ### end Alembic commands ###
